common:
  exp_name: animeface
  path2db: ./../datasets/animeface/data
  path2weight: weight
  batch_size: 64
  start_epoch: 1
  epochs: 10
  evaluate: false
  restart: false
  workers: 16
  seed: 1
  print_freq: 10
  apex: false
  apex_opt_level: O1

optimizer:
  lr: 0.0045
  lr_step_size: 1
  lr_gamma: 0.98
  momentum: 0.9
  weight_decay: 1e-5

model:
  num_classes: 176

preprocess:
  image_size: 256
  crop_size: 224
